# specify a directory to install
cask_args appdir: '/Applications'

brew 'bash'
brew 'bash-completion'
brew 'git'
brew 'hub'
brew 'rbenv'
brew 'tree'
cask 'gitup'
cask 'licecap'

cask 'firefox'
cask 'google-chrome'

cask '1password'
cask 'authy'
cask 'caffeine'
cask 'calibre'
cask 'coconutbattery'
cask 'daisydisk'
cask 'dropbox'
cask 'flux'
cask 'gpg-suite'
cask 'grammarly'
cask 'itsycal'
cask 'michaelvillar-timer'
cask 'rescuetime'
cask 'spectacle'
cask 'the-unarchiver'
cask 'transmission'
cask 'typora'
cask 'vlc'
brew 'ffmpeg'

brew 'mas'
mas 'Shush', id: 496437906
mas 'Keynote', id: 409183694
mas 'Be Focused Pro', id: 961632517

cask 'discord'
cask 'skype'
cask 'slack'

cask 'alfred'
cask 'dash'
cask 'iterm2'
cask 'postman'
cask 'sublime-text'

cask 'spotify'
cask 'steam'

tap 'caskroom/drivers'
cask 'xbox360-controller-driver-unofficial'

tap 'caskroom/fonts'
cask 'font-inconsolata'
cask 'font-fira-code'
cask 'font-hack'
cask 'font-m-plus'
cask 'font-ubuntu'
cask 'font-hermit'

cask 'aerial'
